# Generated by Django 3.1.3 on 2023-05-24 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0007_comment_modify_count'),
        ('pybo', '0007_comment_voter'),
    ]

    operations = [
    ]
