# Generated by Django 4.2.1 on 2023-05-24 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0007_answer_modify_count_question_modify_count'),
        ('pybo', '0008_merge_20230524_1324'),
    ]

    operations = [
    ]
